server:
  port: ${env.server.port:16003}

logging:
  level:
    com.mimiter.mgs.admin:
      repository: debug
    io.swagger.models.parameters.AbstractSerializableParameter: error
  file:
    path: logs
    max-history: 30

spring:
  datasource:
    url: jdbc:mysql://${env.mysql.host:localhost:3306}/mgs?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: ${env.mysql.username:root}
    password: ${env.mysql.password:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: SELECT 1 FROM DUAL
    initialization-mode: never
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  data:
    redis:
      repositories:
        enabled: false
  redis:
    host: ${env.redis.host:localhost}
    port: ${env.redis.port:6379}
    database: 1
    password: ${env.redis.password:}
  cache:
    type: redis
  profiles:
    active: default

mybatis-plus:
  type-enums-package: com.mimiter.mgs.admin.model.enums

mgs.admin:
  cos:
    secret-id: ${env.cos.secret-id:WarningCosSecretIdNotSet}
    secret-key: ${env.cos.secret-key:WarningCosSecretKeyNotSet}
    region: ${env.cos.region:ap-shanghai}
    bucket: ${env.cos.bucket:image-1314089900}

grpc:
  client:
    openDocumentService:
      address: static://${env.grpc.host}
      negotiationType: PLAINTEXT