server:
  port: 16003

logging:
  level:
    com:
      mimiter:
        mgs:
          core:
            repository: debug
  file:
    path: logs
    max-history: 30

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mgs?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: SELECT 1 FROM DUAL
    initialization-mode: never
    platform: mysql
    schema: classpath:db/schema-mysql.sql
    data: classpath:db/data-mysql.sql
  servlet:
    multipart:
      max-file-size: 3MB
  data:
    redis:
      repositories:
        enabled: false
  redis:
    host: localhost
    port: 6379
    database: 0
  cache:
    type: redis
  profiles:
    active: default

mybatis-plus:
  type-enums-package: com.mimiter.mgs.admin.model.entity.enums