server:
  port: ${ENV_SERVER_PORT:16003}

logging:
  level:
    com.mimiter.mgs.admin:
      repository: debug
  file:
    path: logs
    max-history: 30

spring:
  datasource:
    url: jdbc:mysql://${env.mysql.host:localhsost:3306}/mgs?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: ${env.mysql.username:root}
    password: ${env.mysql.password:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: SELECT 1 FROM DUAL
    initialization-mode: never
  servlet:
    multipart:
      max-file-size: 8MB
  data:
    redis:
      repositories:
        enabled: false
  redis:
    host: ${env.redis.host:localhost}
    port: ${env.redis.port:6379}
    database: 0
    password: ${env.redis.password:}
  cache:
    type: redis
  profiles:
    active: default

mybatis-plus:
  type-enums-package: com.mimiter.mgs.admin.model.entity.enums