version: "3"

services:
  registry:
    image: registry:2
    container_name: registry
    ports:
     - 5000:5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    restart: always
    volumes:
      - ./auth:/auth
      - ./data:/data
