DROP TABLE IF EXISTS paragraph;

CREATE TABLE paragraph(
    paragraph_id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    text VARCHAR(255) NOT NULL,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS question;

CREATE TABLE question(
    question_id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    text VARCHAR(255) NOT NULL,
    paragraph_id BIGINT(20) NOT NULL,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX (paragraph_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS answer;

CREATE TABLE answer(
    answer_id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    text VARCHAR(255) NOT NULL,
    start_index INT(11) NOT NULL,
    question_id BIGINT(20) NOT NULL,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX (question_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;