env:
  mysql:
    host: 81.68.137.146:3306
    username: root
    password: k2tNrsL8vet
  redis:
    host: 81.68.137.146
    port: 6379
    password: k2tNrsL8vet
  grpc:
    host: 81.68.137.146:5555

logging:
  level:
    com.mimiter.mgs.core:
      repository: debug
      service: debug
