logging:
  level:
    com:
      mimiter:
        mgs:
          core:
            repository: debug
            service: debug

spring:
  datasource:
    url: jdbc:mysql://106.14.42.183:3306/mgs_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: root
    password: AbstractMGS0926

grpc:
  client:
    myService:
      address: static://106.14.42.183:5555
