env:
  mysql:
    host: localhost:3306
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
  grpc:
    host: 106.14.42.183:5555

server:
  port: 16002

logging:
  level:
    com:
      mimiter:
        mgs:
          core:
            repository: debug
  file:
    path: logs
    max-history: 30


spring:
  application:
    name: mgsbackend-core
  datasource:
    url: jdbc:mysql://${env.mysql.host}/mgs?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: ${env.mysql.username}
    password: ${env.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: SELECT 1 FROM DUAL
    initialization-mode: never
    platform: mysql
    schema: classpath:db/schema-mysql.sql
    data: classpath:db/data-mysql.sql
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 3MB
  data:
    redis:
      repositories:
        enabled: false
  redis:
    host: ${env.redis.host}
    port: ${env.redis.port}
    password: ${env.redis.password}
    database: 0
  cache:
    type: redis
  profiles:
    active: default

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    tags:
      application: ${spring.application.name}

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-enums-package: com.mimiter.mgs.core.model.entity.enums

grpc:
  client:
    myService:
      address: static://${env.grpc.host}
      negotiationType=: PLAINTEXT

mgs:
  weixin:
    appid: wxf2920630b976e003
    secret: 2c8a3a5109c68d9f1a76bc906ee869da
  sms:
    secretId: AKIDxmdMtFRhuxulT8yjItFRQCoMhogPxOgn
    secretKey: 0sBIG5g6KK5f2MVZSCoPtHfu0ynSxMdj
    sdkAppId: 1400746566
    signName: 米弥特
    templateId: 1580939