env:
  mysql:
    host: localhost:3306
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
  grpc:
    host: 106.14.42.183:5555
    payment: localhost:15016

server:
  port: 16002

logging:
  level:
    com.mimiter.mgs.core:
      repository: info
  file:
    path: logs
    max-history: 30


spring:
  application:
    name: mgsbackend-core
  datasource:
    url: jdbc:mysql://${env.mysql.host}/mgs?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: ${env.mysql.username}
    password: ${env.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: SELECT 1 FROM DUAL
    initialization-mode: never
    platform: mysql
    schema: classpath:db/schema-mysql.sql
    data: classpath:db/data-mysql.sql
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 3MB
  data:
    redis:
      repositories:
        enabled: false
  redis:
    host: ${env.redis.host}
    port: ${env.redis.port}
    password: ${env.redis.password}
    database: 0
  cache:
    type: redis
  profiles:
    active: default

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    tags:
      application: ${spring.application.name}

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-enums-package: com.mimiter.mgs.core.model.entity.enums

grpc:
  client:
    myService:
      address: static://${env.grpc.host}
      negotiationType=: PLAINTEXT
    paymentService:
      address: static://${env.grpc.payment}
      negotiation-type: PLAINTEXT

mgs:
  weixin:
    appid:
    secret:
  sms:
    secretId:
    secretKey:
    sdkAppId:
    signName:
    templateId: