logging:
  level:
    com:
      mimiter:
        mgs:
          core:
            repository: debug
            service: debug

spring:
  datasource:
    url: jdbc:mysql://81.68.137.146:3306/mgs?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: root
    password: k2tNrsL8vet

grpc:
  client:
    myService:
      address: static://106.14.42.183:5555
