server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bright_storage?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: root
    password: lcpw_845
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: SELECT 1 FROM DUAL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 3MB
  data:
    redis:
      repositories:
        enabled: false

grpc:
  client:
    myService:
      address: static://localhost:5555